[package]
name = "full-dataset-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scheduled-executor = "0.4.0"
reqwest = {version = "0.11.12", features = ["blocking"]}
httpdate = "1.0.2"